#!/bin/sh
# Hermes container entrypoint.
#
# On FIRST start (empty file share): writes config.yaml from env vars so the
# gateway boots correctly without a manual setup step.
#
# On SUBSEQUENT starts: config.yaml already exists on the persistent file share
# and is left untouched, preserving any changes made via `hermes config set`
# or direct file edits on the share.
#
# Persistent data location: /opt/data  (Azure File Share: hermes-data)
#   /opt/data/config.yaml     — Hermes runtime config (written here on first boot)
#   /opt/data/sessions/       — Conversation session history
#   /opt/data/skills/         — User-installed skill overrides
#   /opt/data/memories/       — Long-term memory blobs (Honcho supplements these)
#
# SQLite main DB lives at /tmp/hermes-state.db (HERMES_DB_PATH) — intentionally
# kept off the Azure File Share because SMB advisory locking causes "database is
# locked" errors.  Honcho (PostgreSQL-backed) provides durable persistence.
#
# To force a config re-initialisation without a full redeploy:
#   az storage file delete \
#     --account-name <storage-account> \
#     --share-name hermes-data \
#     --path config.yaml
# The next container start will regenerate it from env vars.

CONFIG=/opt/data/config.yaml

if [ ! -f "$CONFIG" ]; then
  mkdir -p /opt/data
  cat > "$CONFIG" << EOF
# Hermes runtime config — auto-generated by entrypoint.sh on first boot.
# Edit directly or via: hermes config set <key> <value>

# ── Model ──────────────────────────────────────────────────────────────────────
# OPENAI_MODEL env var selects the router tier: grok | phi4 | kimi | claude
model: ${OPENAI_MODEL:-grok}

# ── Compression ────────────────────────────────────────────────────────────────
# Disabled: grok-4.1-fast-reasoning's context window is large enough that
# compression is not needed, and compression calls add latency.
compression:
  enabled: false
  threshold: 0.75
  target_ratio: 0.35
  protect_last_n: 6
  summary_model: ${OPENAI_MODEL:-grok}

# ── Memory ─────────────────────────────────────────────────────────────────────
memory:
  memory_enabled: true
  user_profile_enabled: true
  memory_char_limit: 900
  user_char_limit: 600
  nudge_interval: 20
  flush_min_turns: 6

# ── Session reset ──────────────────────────────────────────────────────────────
session_reset:
  mode: both
  idle_minutes: 240
  at_hour: 4
  group_sessions_per_user: true

# ── Honcho (self-hosted, PostgreSQL-backed) ────────────────────────────────────
# Self-hosted Honcho; auth is disabled so no api_key is required.
# HONCHO_BASE_URL is injected from the ACA env var at container start time.
honcho:
  enabled: ${HONCHO_ENABLED:-true}
  base_url: ${HONCHO_BASE_URL:-}

# ── Vision ─────────────────────────────────────────────────────────────────────
auxiliary:
  vision:
    provider: auto
    model: ''
    timeout: 15
EOF
  echo "[entrypoint] First run — initialised /opt/data/config.yaml (model=${OPENAI_MODEL:-grok})"
fi

exec "$@"
