#!/bin/sh
# write-hermes-config.sh — generate the Hermes CLI config.yaml in the
# ROUTER-COMPATIBLE shape (custom provider + chat_completions + Bearer api_key).
#
# Called by docker-entrypoint.sh at container start. Kept as a standalone
# script so the generated template shape is unit-testable outside the
# container (tests/paperclip/hermes-config-template.test.mjs).
#
# Ported from upstream private deployment incident learnings (2026-07):
# Hermes v0.18.x sends x-api-key — NOT "Authorization: Bearer" — for the
# custom provider when api_mode is anthropic_messages, and it resolves the
# key from ~/.hermes/.env ANTHROPIC_* vars (absent in this container), so
# every agent model call died 401 against the model router's fail-closed
# bearer auth. The failure surfaced at agent spawn as adapter_failed.
#
# The proven-good shape is the plain OpenAI chat-completions mode with
# api_key set: the OpenAI SDK sends Bearer auth the router accepts, and the
# router serves every model tier on /v1/chat/completions.
#
# api_mode is pinned EXPLICITLY: without it, Hermes v0.18.x still picks the
# Anthropic /v1/messages transport for tool-heavy runs, which re-triggers the
# x-api-key 401.
#
# TRADE-OFF: api_mode anthropic_messages (and its cache_control prompt-cache
# injection for Claude tiers) stays OFF until the router also accepts
# x-api-key auth — restoring it without that router change re-breaks all
# agent runs.
set -eu

HERMES_CONFIG_DIR="${HERMES_HOME:-/paperclip/.hermes}"
HERMES_CONFIG="${HERMES_CONFIG_DIR}/config.yaml"
mkdir -p "${HERMES_CONFIG_DIR}"

# Router base URL (OpenAI-compatible /v1 root). Terraform sets OPENAI_BASE_URL
# on the container; HERMES_BASE_URL overrides it for non-default layouts.
HERMES_BASE_URL_DEFAULT="${HERMES_BASE_URL:-${OPENAI_BASE_URL:-http://ca-hermes-dev/v1}}"

# Router API key: ROUTER_API_KEY wins; fall back to OPENAI_API_KEY (the
# Terraform module already mounts the router key secret there for the
# adapter's inherited env). Empty key = every agent run 401s (fail-closed),
# so warn loudly rather than silently writing a dead config.
HERMES_ROUTER_API_KEY="${ROUTER_API_KEY:-${OPENAI_API_KEY:-}}"
if [ -z "${HERMES_ROUTER_API_KEY}" ]; then
  echo "[write-hermes-config] WARNING: ROUTER_API_KEY/OPENAI_API_KEY unset — Hermes agent runs will 401 against the model router (fail-closed)." >&2
fi

cat > "${HERMES_CONFIG}" <<HERMES_EOF
# Auto-generated by write-hermes-config.sh — do not edit manually.
# Routes all model requests through the model router sidecar using OpenAI
# chat-completions + Bearer auth (see that script's header for the incident
# that mandates this exact shape).
model:
  provider: custom
  base_url: ${HERMES_BASE_URL_DEFAULT}
  api_mode: chat_completions
  api_key: ${HERMES_ROUTER_API_KEY}
prompt_caching:
  cache_ttl: 1h
HERMES_EOF
chown node:node "${HERMES_CONFIG}" 2>/dev/null || true
echo "[write-hermes-config] Wrote Hermes config at ${HERMES_CONFIG} (provider=custom api_mode=chat_completions base_url=${HERMES_BASE_URL_DEFAULT})"
